version: '3.7'

services:
  mqtt:
    container_name: mosquitto
    image: arm64v8/eclipse-mosquitto:2.0.15
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
  database:
    build: ./
    ports:
      - 3000:3000
    volumnes:
     - ./database:/usr/src/app

volumes:
  config:
  data:
  log:
