version: '3.7'

services:
  mqtt:
    container_name: mosquitto
    image_name: eclipse-mosquitto:2.0.15
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/nguyentruong/homestats-mqtt-server/mqtt/config:/mosquitto/config
      - /home/nguyentruong/homestats-mqtt-server/mqtt/data:/mosquitto/data
      - /home/nguyentruong/homestats-mqtt-server/mqtt/log:/mosquitto/log
volumes:
  config:
  data:
  log:
