version: '2'

services:
  mqtt:
    container_name: mosquitto
    image: arm64v8/eclipse-mosquitto:2.0.15
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
volumes:
  config:
  data:
  log:
