version: '3.7'

services:
  mqtt:
    container_name: mosquitto
    image: arm64v8/eclipse-mosquitto:2.0.15
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
  database:
    container_name: database
    build: ./database
    restart: always
    ports:
      - 3000:3000
    environment:
      AWS_PROFILE: "${AWS_PROFILE:-test}"
    volumes:
      - ./.aws/:/root/.aws:ro
      - ./database:/usr/src/database
    depends_on:
      - mqtt
  # database-cron:
  #   container_name: database-cron
  #   build: ./database-cron
  #   environment:
  #     AWS_PROFILE: "${AWS_PROFILE:-test}"
  #   volumes:
  #     - ./.aws/:/root/.aws:ro
  #     - ./database:/usr/src/database
  #     - ./database-cron:/usr/src/database-cron
  #   depends_on:
  #     - database
volumes:
  config:
  data:
  log:
